name: Discord Push Notifier

on:
  push:
    branches:
      - main  # μ•λ λ°›μ„ λΈλμΉ

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        uses: actions/http-client@v2
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          method: POST
          headers: '{"Content-Type": "application/json"}'
          body: |
            {
              "username": "μ•„λ¦¬μ¤",
              "avatar_url": "https://img.onnada.com/2022/0917/thumb_991469724_8c321a73_AIwLeP.jpg",
              "content": "π“ μ©μ‚¬ μ•„λ¦¬μ¤ μ»¤λ°‹ ν™•μΈν–μµλ‹λ‹¤!\nμ»¤λ°‹ λ©”μ‹μ§€: ${{ github.event.head_commit.message }}\nμ‘μ„±μ: ${{ github.actor }}"
            }
