name: Discord Push Notifier

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: peter-evans/discord-webhook@v2
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: "μ•„λ¦¬μ¤"
          avatar-url: "https://img.onnada.com/2022/0917/thumb_991469724_8c321a73_AIwLeP.jpg"
          content: |
            π“ μ©μ‚¬ μ•„λ¦¬μ¤ μ»¤λ°‹ ν™•μΈν–μµλ‹λ‹¤!
            μ»¤λ°‹ λ©”μ‹μ§€: ${{ github.event.head_commit.message }}
            μ‘μ„±μ: ${{ github.actor }}
