name: Discord Push Notifier

on:
  push:
    branches:
      - main  # ì•ŒëŒ ë°›ì„ ë¸Œëœì¹˜

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: peter-evans/discord-webhook@v2
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}  # ë“±ë¡í•œ Secret ì´ë¦„
          username: "ì•Œë¦¼ë´‡"  # Discordì— í‘œì‹œí•  ì´ë¦„
          avatar-url: "https://img.onnada.com/2022/0917/thumb_991469724_8c321a73_AIwLeP.jpg"  # Discordì— í‘œì‹œí•  í”„ë¡œí•„ ì‚¬ì§„
          content: |
            ğŸ“Œ ìƒˆë¡œìš´ ì»¤ë°‹ì´ ê°ì§€ë˜ì—ˆìŠµë‹ˆë‹¤!
            ì»¤ë°‹ ë©”ì‹œì§€: ${{ github.event.head_commit.message }}
            ì‘ì„±ì: ${{ github.actor }}
